"""create_daily_journals_table

Revision ID: 16fa853ccab1
Revises: f7c93abaa40e
Create Date: 2026-09-08 22:09:39.685115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16fa853ccab1'
down_revision: Union[str, Sequence[str], None] = 'f7c93abaa40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_journals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('point_win', sa.Text(), nullable=False),
    sa.Column('point_insight', sa.Text(), nullable=False),
    sa.Column('point_improvement', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_date', name='uq_user_journal_date')
    )
    op.create_index(op.f('ix_daily_journals_entry_date'), 'daily_journals', ['entry_date'], unique=False)
    op.create_index(op.f('ix_daily_journals_id'), 'daily_journals', ['id'], unique=False)
    op.create_index(op.f('ix_daily_journals_user_id'), 'daily_journals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_journals_user_id'), table_name='daily_journals')
    op.drop_index(op.f('ix_daily_journals_id'), table_name='daily_journals')
    op.drop_index(op.f('ix_daily_journals_entry_date'), table_name='daily_journals')
    op.drop_table('daily_journals')
    # ### end Alembic commands ###
